### ISSUE TITLE
2.4 정규화와 피드 포워드 층 오타입니다!

### ISSUE THREAD

**Issue by pythaac** [onlybooks/llm#13]
2.4 정규화와 피드 포워드 층 (pp.85 3번째 줄)에서 아래와 같은 오타가 있습니다!

### As-is
이때 토큰 임베딩 차원(**hidden_dim**)을 인자로 전달했고, ...

### To-be
이때 토큰 임베딩 차원(**embedding_dim**)을 인자로 전달했고, ...

https://github.com/onlybooks/llm/blob/9524d5d4ee21530c86e5a2e86a1890891f5021bb/02%E1%84%8C%E1%85%A1%E1%86%BC/chapter_2_transformer_with_code.ipynb#L300-L309

**Comment by shangrilar** [comment]
안녕하세요. 허정준입니다.
오타 제보 감사드립니다 :)

정오표에 반영하도록 하겠습니다~!
즐거운 휴일 보내시길 바랍니다.
감사합니다.
