### ISSUE TITLE
7장 패키지 설치에 문제가 있습니다.

### ISSUE THREAD

**Issue by acciofreedom** [onlybooks/llm#14]
안녕하세요?
7장  예제 7-02를 실행해 보니 model 생성할 때 auto-gptq 버전이 0.3.1이 설치돼 버전이 맞지 않는다는 에러메시지가 나왔습니디.
auto-gptq를 제거하고, 책에 있는 설치 코드대로 따라해 보니 "auto-gptq 0.7.1을 찾을 수 없다는 빨간색 메시지가 나오면서 설치 중단좼습니다. 제 컴퓨터의 CUDA 버전은 12.3.3이고, 오늘은 2024년 10월 6일입니다. 감사합니다.

**Comment by shangrilar** [comment]
안녕하세요. 허정준입니다.
질문주셔서 감사합니다 :)

auto-gptq 0.7.1 버전이 해당 라이브러리 최신 버전이고 24년 3월 이후 변경이 없어서 라이브러리 쪽 문제는 아닌 것으로 보입니다.
구글 코랩에서 확인해봤을 때 CUDA 버전 12.2에서 잘 설치가 되는 것을 확인했습니다.

라이브러리의 깃허브에서 아래와 같이 설치 관련 부분을 참고하셔서 문제를 해결해보시는게 좋을 것 같습니다.
https://github.com/AutoGPTQ/AutoGPTQ?tab=readme-ov-file#installation

혹시 문제가 해결이 안 되시는 경우 말씀 부탁드립니다.
감사합니다~!

**Comment by acciofreedom** [comment]
답변 감사합니다. 문제는 auto-gptq 0.7.1이 설치되지 않고 0.3.1이 설치되고 있다는 겁니다.
보여주신 링크에 있는 CUDA 12.1 설치 코드를 복사해 붙여 넣기하고 나니 뭔가 진행되고 나서 
"Successfully installed auto-gptq-0.3.1"가 나오고 나서 명령프롬프트가 나타납니다. 
그리고 나서 예제 7.02를 실행하니
"Found an incompatible version of auto-gptq. Found version 0.3.1, but only version above 0.4.99 are supported" 라는 에러 메시지가 나고 있습니다.
Anaconda에 새로운 환경을 만들어 진행해도 달라지지 않고 있습니다,.
이게 코랩에서 하는 게 권장되는 일을, 제 PC, 그것도 window 11에서 수행했으므로 발생한 문제일까요?
하여튼 더 이상의 실습을 진행해 보지 못하고 있는 상태입니다. 
제가 받은 느낌은, 저자님께서 당장 해결책을 주실 수 있는 문제 같지 않다는 것이지만, 저처럼 자신의 PC에서 이 책을 공부해 가는 사람에게는 이런 문제로 인해 책의 가치를 더 알아가지 못하는 상황도 발생할 수 있다는 점을 말씀드리는 것으로 그쳐야 할 거 같네요. 감사합니다.

**Comment by shangrilar** [comment]
넵 환경 세팅에 문제가 있어 답답하신 마음은 충분히 이해가 됩니다.

다만, 프로그래밍에서 가장 어려운 것이 설치와 환경 세팅이라는 농담을 할 정도로 코드가 실행되도록, 또 동일한 실행 결과가 나오도록 하는 것은 까다로운 작업입니다. 그래서 저희 책을 포함해 대부분의 책과 강의가 실습 환경을 먼저 정하고 최대한 환경 세팅으로 인한 혼동을 줄인 상태에서 전달하고자 하는 지식과 메시지에 집중하실 수 있도록 안내하고 있습니다.

저도 많은 책과 강의를 접해봤기 때문에 로컬 환경에서 코드를 실행하고 싶다는 마음은 충분히 공감합니다. 
하지만 환경 세팅의 어려움으로 학습 진행이 되지 않는 상황이시라면, 먼저 실습 환경에서 학습을 진행하시는 걸 추천드립니다.

환경 세팅 과정의 에러 해결에 도움이 되지 못한 점 양해 부탁드립니다~!
감사합니다.
