### ISSUE TITLE
2장  예제 2.13번 질문 드립니다.

### ISSUE THREAD

**Issue by Hong0331** [onlybooks/llm#18]
``` python
def compute_attention(querys, keys, values, is_causal=False):
	dim_k = querys.size(-1) # 16
	scores = querys @ keys.transpose(-2, -1) / sqrt(dim_k) # (1, 5, 5)
	print(querys.size())
	if is_causal:
		query_length = querys.size(2)
		key_length = keys.size(2)
		temp_mask = torch.ones(query_length, key_length, dtype=torch.bool).tril(diagonal=0)
		scores = scores.masked_fill(temp_mask == False, float("-inf"))
	weights = F.softmax(scores, dim=-1) # (1, 5, 5)
	return weights @ values # (1, 5, 16)
```
이 코드에서 querys.size(2)와 keys.size(2)는 16이어서 실제로 코드를 돌려봤을 때 오류가 뜨는데, 1로 바뀌어야 하지 않나해서 질문드립니다.
좋은 책 감사합니다.

**Comment by shangrilar** [comment]
안녕하세요. 허정준입니다.
문의 남겨주셔서 감사합니다.

네 지금 코드를 봤을 때 2를 -2로 변경해서 실행하는 것이 맞아 보입니다.

query_length = querys.size(-2)
key_length = keys.size(-2)

해당 코드에서는 1로 변경하셔도 괜찮은데요. 
멀티 헤드 어텐션에서는 size(1), 즉 두 번째 값으로 다른 값이 올 수 있어서 -2로 변경하는 것이 더 좋아 보입니다.

오류 제보해주셔서 감사합니다 :)
정오표에 반영하고 수정하도록 하겠습니다.

감사합니다.
허정준 드림
