### ISSUE TITLE
선생님 2.3.2절부터 외계어로 보이는데 접어야할까요

### ISSUE THREAD

**Issue by devkanghk** [onlybooks/llm#19]
AI에 관심이 생겨 이 책을 읽기 시작했는데 트랜스포머 아키텍쳐 들어가면서 이해하기가 힘들어지네요.
토큰 임베딩, 위치 임베딩까지는 어느 정도 이해하고 넘어갔는데 어텐션 나오면서 부터 안드로메다로 가버리네요.
몇번 더 읽어보면 이해가 될까요? 
혹시 참고할만한 자료가 또 있을까요?
GPT에게 물어보면서 공부해야할까요?
아니면 지금이라도 접고 다른 기술을 배우러 가야할까요.
이거 읽고 이해하신 분들은 다들 머리가 좋으신 분들인가 자괴감이 드네요.

**Comment by shangrilar** [comment]
안녕하세요. 허정준입니다.
문의 남겨주셔서 감사합니다.

트랜스포머와 어텐션의 경우 처음 접했을 때 이해하는 것이 쉽지 않은데요.
이번이 처음 공부하시는 것이라면 2장은 가볍게 읽고 넘어가시는 걸 추천드립니다.

어텐션 연산을 직관적으로 설명하면, "문장의 맥락을 각 단어에 반영한다" 인데요. 
문장의 맥락을 반영하기 위해서 "문장 내에 서로 관련이 있는 단어들끼리 섞는" 방법을 사용합니다.
"서로 관련이 있는 단어"를 찾는 걸 마치 저희가 구글링으로 원하는 정보를 검색하는 것과 유사하게 처리해보겠다는 접근 방식입니다.

처음이시라면 지금은 느낌 정도만 가지고 가셔도 충분합니다.

트랜스포머와 어텐션 관련해서 가장 유명한 참고 자료는 아래 사이트입니다.
https://jalammar.github.io/illustrated-transformer/

혹시 더 궁금하신 점이 있다면 말씀 부탁드립니다 :)
감사합니다.
허정준 드림
