### ISSUE TITLE
6장 실습중 문의가 있어 남깁니다.

### ISSUE THREAD

**Issue by sundonghwan** [onlybooks/llm#2]
안녕하세요.  LLM 애플리케이션 개발과 관련된 양질의 정보를 담긴 책을 내주셔서 정말 감사드립니다.

실습 중에 문의 사항이 있어 글을 남깁니다.

6장 예제 6.11의 LoRa 어댑터 결합 및 허깅페이스 허브 업로드 코드 중

1. 변수 start_model은 학습 시 활용한 모델 명으로 지정하면 되는 걸까요?
2. 노트북 파일에서도 new_model 변수는 따로 할당되어 있는 것 같지 않은데 어떠한 데이터를 넣으면 될까요?

감사합니다

**Comment by shangrilar** [comment]
안녕하세요. 허정준입니다.
먼저, 책의 이슈 공유해주셔서 감사하고 혼동을 드려 죄송합니다.

코드의 의미를 더 명확하게 만들기 위해 변수의 이름을 변경하던 중 놓친 부분이 있었습니다.
아래와 같이 변수 이름을 변경하시면 코드의 다른 부분과 변수 일치가 가능합니다.
start_model -> base_model
new_model -> finetuned_model

전달드린 방식으로 문제 해결이 안 되는 경우 다시 한 번 이슈 공유 부탁드립니다.
감사합니다.
