### ISSUE TITLE
안녕하세요. 6장 문의 있습니다.

### ISSUE THREAD

**Issue by hyunkoome** [onlybooks/llm#3]
안녕하세요.

정말 책 잘 읽고있습니다. 너무 좋은 책 제공해주셔서 너무너무 감사합니다.

다름이 아니라, p 224의 "6.3.3 학습 데이터 정제와 미세조정" 챕터에서 
GPT4 를 활용해 데이터 필터링을 수행하여 정제한 데이터셋을 만드셨다고 하셨는데,
어떻게 진행하는 지 알수있는 추가 자료가 있는지 문의드립니다.

저도 한번 해보고 싶어서요. ^^

미리 감사드립니다.

**Comment by shangrilar** [comment]
안녕하세요. 허정준입니다.

책 잘 읽고 계시다니 정말 감사합니다 :)

데이터셋을 만든 과정을 조금더 설명드리겠습니다.
처음에 데이터셋을 생성했을 때 45,000개 정도의 데이터셋이 있었고, 그 중에서 규칙 기반으로 먼저 필터링을 했습니다.
이때는 SQL의 규칙을 사용했습니다. 예를 들어, "SELECT" 나 "FROM" 같은 필수적인 문자열이 있는지, "JOIN"이 있으면 "ON" 조건이 함께 있는지 등을 점검했습니다.

다음으로 말씀해주신 부분의 필터링을 할 때는 (DDL, 자연어 쿼리, SQL 쿼리)를 함께 넣고 SQL 쿼리가 자연어 쿼리의 요구사항을 해결할 수 있는지 확인하고, 해결된다면 'yes', 아니라면 'no'를 반환하도록 해서 'yes' 인 데이터만 남기는 방식을 사용했습니다.

실습을 만들 당시에는 mini 모델이 없었는데 이제는 mini 모델이 있어 비교적 적은 비용으로 시도해보실 수 있을 것 같습니다 :)

혹시 더 도움이 필요하시면 말씀 부탁드립니다.
감사합니다~!

**Comment by hyunkoome** [comment]
@shangrilar 답변 감사합니다.

6장 돌려보고있는데, 책 쓰실때 대비, 현재 패키지들의 버전들이 달라져서.. 삽질하면서 패키지 버전들 맞추고있습니다.ㅎ
다름이 아니라, 책에는 1epoch 정도만 돌려보던데, 성능이 어느정도 나오게 하려면 몇 epochs 정도는 돌려야 하나요??

원래 저는, 이미지, 라이다 등.. 일종의 멀티모달..데이터만 다루다가. text 등을 해보려고하니, 아직..epochs 감이 없네요^^

감사합니다.

**Comment by shangrilar** [comment]
Q. 혹시 6장 초반에 고정한 패키지 버전으로 설치가 안 돼서 패키지 버전을 맞추는 과정을 진행 중이신걸까요??

그리고 학습 에포크 관련해서 말씀드리면,
실습의 목적이 sLLM을 학습시키기 위한 실습 데이터를 준비하고 학습을 진행하는 전체 과정을 보여드리기 위함이었고, 성능을 최대한 끌어올리려는 목적은 아니어서 1 에포크 만 학습을 시켰습니다. 저도 에포크를 변경시키면서 실험을 다양하게 하지 않아 최적의 에포크를 답변드리기는 어려운데요. 책의 표 6.3에서 데이터셋의 크기를 변경시키면서 학습시켰을 때 80% -> 100%로 데이터 양을 증가시켰을 때 성능 향상이 있었기 때문에 에포크를 좀더 늘려도 성능 향상의 여지는 남아있지 않을까 싶습니다.

질문 주신 부분에 대한 시원한 답은 아닐 것 같은데 혹시 다양하게 실험해보시다가 인사이트 발견하시면 저한테도 공유 부탁드립니다 :)

감사합니다.

**Comment by hyunkoome** [comment]
@shangrilar 
아무래도 개발환경(os, cuda, gpu 등)이 다르다보니, 패키지를 다르게 맞춰줘야하나 봅니다. ^^

저는 아래와 같이 맞추니 무리없이 거의 모든 코드가 동작되었습니다. 
https://github.com/hyunkoome/Study_LLM/blob/d6398231b4bc72e08d8357d8779b34a7e98e7b61/requirements.txt#L10

일부 수정된 부분은 실습하면서, 제 저장소(https://github.com/hyunkoome/Study_LLM) 정리를 해두었는데요.
크리티컬한 부분은 없었습니다.

기억 나는 것은..(버전의 차이일 수도 있는데요 ^^;)
11장에서, sentence-transformers 라이브러리의 CrossEncoder 클래스는 fit 메서드를 호출할 때 모델을 저장하는 메커니즘이 없어서,
                학습 후에 모델을 수동으로 저장해야 했습니다.
https://github.com/hyunkoome/Study_LLM/blob/d6398231b4bc72e08d8357d8779b34a7e98e7b61/src/example_11_create_embedding_models_using_own_datasets_03_finetuned_basis_embedding_model_for_cross_encoder.py#L102

여튼. 3년내 읽은 IT 책 중에 가장 좋았습니다.
좋은 책 제공해주셔서 감사합니다^^

**Comment by shangrilar** [comment]
@hyunkoome 
상세한 설명 감사드립니다~!

공부하시는데 책이 도움이 된 것 같아 정말 다행입니다 :)
혹시 더 궁금한 점 생기시면 편하게 말씀 부탁드립니다.
감사합니다.
