### ISSUE TITLE
예제 3.16 로컬의 데이터 활용하기 

### ISSUE THREAD

**Issue by wonyang-lee** [onlybooks/llm#5]
Colab 에서 실행하면 아래와 같은 에러가 납니다.

실습 PC 에서의 파일 절대 경로 /content/ 의  경로의 위치가 알고 싶습니다.
my_file.csv 파일 샘플도 있으면 좋을 것 같습니다. 

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-33-0fa88f1e16f8>](https://localhost:8080/#) in <cell line: 3>()
      1 from datasets import load_dataset
      2 # 로컬의 데이터 파일을 활용
----> 3 dataset = load_dataset("csv", data_files="my_file.csv")
      4 
      5 # 파이썬 딕셔너리 활용

6 frames
[/usr/local/lib/python3.10/dist-packages/datasets/data_files.py](https://localhost:8080/#) in resolve_pattern(pattern, base_path, allowed_extensions, download_config)
    405         if allowed_extensions is not None:
    406             error_msg += f" with any supported extension {list(allowed_extensions)}"
--> 407         raise FileNotFoundError(error_msg)
    408     return out
    409 

FileNotFoundError: Unable to find '/content/my_file.csv'

**Comment by shangrilar** [comment]
안녕하세요. 허정준입니다.
문의 사항 공유해주셔서 감사합니다.

해당 코드 부분은 아래의 데이터를 쉽게 허깅페이스 데이터셋 형식으로 변환해 활용할 수 있다는 예시를 보여드리기 위한 부분이고 실제 동작시키려면 말씀해주신대로 csv 파일이 필요합니다.
- 로컬에 있는 파일
- 판다스 데이터프레임
- 파이썬 데이터 타입

임의의 csv 파일을 구글 코랩에 업로드하신 후 파일 이름만 my_file.csv 에서 업로드하신 파일 이름으로 변경하시면 동작할 것입니다.

이 부분이 명확히 전달되지 않은 것 같아 코드에 안내를 추가하도록 하겠습니다.
혹시 더 궁금하신 점이 있다면 말씀 부탁드립니다.
감사합니다.
