### ISSUE TITLE
523 페이지에 나오는 표 16.1 에 RNN 의 장점이라고 적힌 내용을 확인바랍니다.

### ISSUE THREAD

**Issue by idgmatrix** [onlybooks/llm#7]
표 16.1에 RNN의 장점으로 "추론이 효율적(시퀀스 길이에 관계없이 일정한 시간)"이라고 되어 있는데 RNN은 시퀀스를 하나씩 순차적으로 처리하기 때문에 시퀀스가 길어지면 처리에도 더 오래 걸리지 않나요?! 내용 확인 바랍니다.

표 16.4 에도 RNN의 특징에 추론 연산량이 일정하다고 되어 있습니다. 이것도 확인 바랍니다.

**Comment by shangrilar** [comment]
안녕하세요. 허정준입니다.
문의 남겨주셔서 감사합니다 :)

의도했던 의미는 단위 토큰당(토큰 1개 추가 생성당) 연산량이 일정하다는 것이었는데요.
말씀해주신 표와 앞뒤의 맥락에 그 부분이 표현되지 않아 혼동을 드리게 됐습니다. 혼동을 드려 죄송합니다.

표에서 설명하고자 한 내용을 풀어서 말씀드리면 아래와 같습니다.
RNN은 하나의 토큰을 추가로 생성할 때 잠재 상태와 토큰 임베딩을 모델에서 연산하여 결과를 출력하기 때문에 매번 일정한 연산량이 필요합니다.
반면, 트랜스포머는 하나의 토큰을 추가로 생성할 때 시퀀스 길이에 비례해서 연산량이 증가합니다.

의도한 의미를 충분히 전달할 수 있도록 본문과 표의 표현을 수정해보겠습니다.

혹시 더 확인이 필요하신 사항이 있다면 말씀 부탁드립니다.
감사합니다~!

**Comment by idgmatrix** [comment]
자세한 답변 감사합니다.

이해했습니다. 토큰 하나 생성당 필요한 연산량을 기준으로 하신 거군요.
저처럼 표만 보면 그런 걸 알기 어렵기 때문에 해당 기준을 명시해주시면 더 좋을 듯합니다.
