### ISSUE TITLE
그림2.2 오탈자

### ISSUE THREAD

**Issue by Snupee** [onlybooks/llm#8]
그림 2.2 각 구성요소를 설명해줄 절을 하나씩 늘여야할 것 같습니다. 
임베딩 2.1절 ->2.2절 ~ 디코더 2.5절->2.6절

아직 2장 보고 있는데 너무 좋습니다. 감사합니다.

**Comment by shangrilar** [comment]
안녕하세요. 허정준입니다.
오류 제보해주셔서 감사합니다 :)

말씀해주신 내용 정오표에 반영하겠습니다.
그리고 좋은 평가 해주셔서 감사합니다!

추가로 잘못된 내용이 있거나 궁금하신 사항 생기시면 언제든 문의 남겨주세요.
감사합니다.
