### ISSUE TITLE
Numpy version에 따른 이슈 있습니다.

### ISSUE THREAD

**Issue by taewanHwang** [onlybooks/llm#9]
05장 예시 실행시 numpy version latest(2.x version)로 실행하면, 다음과 같은 에러 발생합니다. 
---
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 5
      2 print_gpu_utilization()
      4 for batch_size in [4, 8, 16]:
----> 5     gpu_memory_experiment(batch_size)
      7     torch.cuda.empty_cache()

Cell In[8], line 25
     16 training_args = TrainingArguments(
     17     per_device_train_batch_size=batch_size,
     18     gradient_accumulation_steps=gradient_accumulation_steps,
   (...)
     21     num_train_epochs=1
     22   )
     24 try:
---> 25     train_model(model, dataset, training_args)
     26 except RuntimeError as e:
     27     if "CUDA out of memory" in str(e):

Cell In[5], line 9
      7 model.train()
      8 gpu_utilization_printed = False
----> 9 for step, batch in enumerate(train_dataloader, start=1):
     10     batch = {k: v.to(model.device) for k, v in batch.items()}
...
--> 197 return np.array(array, copy=False)

ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
---
해결하기 위해서 numpy version 1.x로 낮추면 동작합니다. (Numpy 1.26.3 test시 동작)

**Comment by shangrilar** [comment]
안녕하세요. 허정준입니다.
제보해주셔서 감사합니다 :)

아직 책의 실습 환경인 구글 코랩에서는 numpy 버전이 1.26.X 여서
우선은 로컬에서 실습하시는 분들을 위해 버전 변경에 따른 안내를 추가하고
추후 구글 코랩 numpy 버전이 올라가면 맞춰서 코드를 수정하도록 하겠습니다.

제보 감사드리고 즐거운 연휴 보내시길 바랍니다~!
감사합니다.

**Comment by dcrobot-keen** [comment]
요게 아직 해결 안된거 같은데, 이슈는 close 된 거 같습니다.
